export const TOPICS = [
  { id: "general", en: "General", zh: "總論" },
  { id: "head", en: "Head", zh: "頭部" },
  { id: "neck", en: "Neck and back", zh: "頸與背" },
  { id: "thorax", en: "Thorax", zh: "胸" },
  { id: "abdomen", en: "Abdomen", zh: "腹" },
  { id: "pelvis", en: "Pelvis and perineum", zh: "骨盆與會陰" },
  { id: "upper", en: "Upper limb", zh: "上肢" },
  { id: "lower", en: "Lower limb", zh: "下肢" },
  { id: "nerves", en: "Nerves", zh: "神經" },
  { id: "vessels", en: "Vessels", zh: "血管" },
];

function bone(id, topicId, mesh, en, zh, explainEn, explainZh, choices) {
  const topic = TOPICS.find((entry) => entry.id === topicId);
  return {
    id,
    topicId,
    region: topic.en,
    regionZh: topic.zh,
    meshes: [mesh],
    model: null,
    promptEn: "Which structure is lit?",
    promptZh: "亮起的是哪一個結構？",
    en,
    zh,
    explainEn,
    explainZh,
    choices,
  };
}

function study(id, topicId, model, promptEn, promptZh, en, zh, explainEn, explainZh, choices) {
  const topic = TOPICS.find((entry) => entry.id === topicId);
  return {
    id,
    topicId,
    region: topic.en,
    regionZh: topic.zh,
    meshes: null,
    model,
    promptEn,
    promptZh,
    en,
    zh,
    explainEn,
    explainZh,
    choices,
  };
}

const muscles = [
  ["Muscles of the thorax, abdomen and back", "胸、腹與背部的肌肉"],
  ["Rotator cuff", "旋轉袖"],
  ["Adductors of the thigh", "大腿內收肌"],
  ["Brachial plexus", "臂神經叢"],
];

const attachments = [
  ["Muscle origins and insertions", "肌肉的起點與止點"],
  ["Only the joint capsules", "只有關節囊"],
  ["The nerve roots", "神經根"],
  ["Arterial anastomoses", "動脈吻合"],
];

export const QUESTIONS = [
  bone("c7", "general", "Cervical vertebrae (C7)", "Seventh cervical vertebra", "第七頸椎",
    "The vertebra prominens is the bony point at the base of the neck.",
    "隆椎是頸根可觸及的骨性隆起。",
    [["Seventh cervical vertebra", "第七頸椎"], ["Atlas", "寰椎"], ["First thoracic vertebra", "第一胸椎"], ["Third lumbar vertebra", "第三腰椎"]]),
  bone("t7", "general", "Thoracic vertebrae (T7)", "Seventh thoracic vertebra", "第七胸椎",
    "A mid-thoracic vertebra. Its rib helps form the middle of the cage.",
    "位於胸段中部的椎骨，其肋骨參與構成胸廓中段。",
    [["Seventh thoracic vertebra", "第七胸椎"], ["Seventh cervical vertebra", "第七頸椎"], ["Third lumbar vertebra", "第三腰椎"], ["Sacrum", "薦骨"]]),
  bone("l3", "general", "Lumbar vertebrae (L3)", "Third lumbar vertebra", "第三腰椎",
    "A large lumbar vertebra behind the abdomen. It carries the weight of the trunk.",
    "粗大的腰椎位於腹後，承受軀幹的重量。",
    [["Third lumbar vertebra", "第三腰椎"], ["Twelfth thoracic vertebra", "第十二胸椎"], ["Sacrum", "薦骨"], ["Axis", "樞椎"]]),
  bone("sternum", "general", "Body of sternum", "Body of the sternum", "胸骨體",
    "The long middle piece of the sternum, in the front of the chest.",
    "胸骨體是胸骨中間的長段，位於胸前正中。",
    [["Body of the sternum", "胸骨體"], ["Manubrium", "胸骨柄"], ["Clavicle", "鎖骨"], ["Fifth rib", "第五肋"]]),
  study("typical-vertebra", "general", "vertebrae",
    "In this comparison of typical vertebrae, which one carries a facet for a rib?",
    "在這組典型椎骨裡，哪一種帶有與肋骨相接的關節面？",
    "Thoracic vertebra", "胸椎",
    "A typical thoracic vertebra has costal facets. Cervical and lumbar vertebrae do not.",
    "典型胸椎有肋凹。頸椎與腰椎沒有。",
    [["Thoracic vertebra", "胸椎"], ["Cervical vertebra", "頸椎"], ["Lumbar vertebra", "腰椎"], ["Coccyx", "尾骨"]]),

  bone("frontal", "head", "Frontal bone", "Frontal bone", "額骨",
    "It forms the forehead and the roof of each orbit.",
    "額骨構成前額，並形成兩側眼眶的頂。",
    [["Frontal bone", "額骨"], ["Parietal bone", "頂骨"], ["Occipital bone", "枕骨"], ["Nasal bone", "鼻骨"]]),
  bone("parietal", "head", "Parietal bone right", "Parietal bone", "頂骨",
    "The two parietal bones meet at the top of the cranial vault.",
    "左右頂骨在顱頂相接，構成顱蓋的上部。",
    [["Parietal bone", "頂骨"], ["Frontal bone", "額骨"], ["Temporal bone", "顳骨"], ["Occipital bone", "枕骨"]]),
  bone("occipital", "head", "Occipital bone", "Occipital bone", "枕骨",
    "It forms the back and the base of the cranium. Turn the model to see it.",
    "枕骨構成顱腔的後壁與底部。把模型轉到後方即可看見。",
    [["Occipital bone", "枕骨"], ["Parietal bone", "頂骨"], ["Sphenoid bone", "蝶骨"], ["Mandible", "下頜骨"]]),
  bone("temporal", "head", "Temporal bone.r", "Temporal bone", "顳骨",
    "It forms the side of the cranium, houses the ear, and meets the jaw.",
    "顳骨構成顱腔側壁，容納耳的結構，並與下頜相接。",
    [["Temporal bone", "顳骨"], ["Zygomatic bone", "顴骨"], ["Parietal bone", "頂骨"], ["Maxilla", "上頜骨"]]),
  bone("zygomatic", "head", "Zygomatic bone.r", "Zygomatic bone", "顴骨",
    "The cheek bone forms the lateral rim of the orbit.",
    "顴骨構成面頰，並形成眼眶的外側緣。",
    [["Zygomatic bone", "顴骨"], ["Nasal bone", "鼻骨"], ["Maxilla", "上頜骨"], ["Mandible", "下頜骨"]]),
  bone("maxilla", "head", "Maxilla bone.r", "Maxilla", "上頜骨",
    "The upper jaw holds the upper teeth and forms the floor of the orbit.",
    "上頜骨承載上排牙齒，並構成眼眶的底。",
    [["Maxilla", "上頜骨"], ["Mandible", "下頜骨"], ["Zygomatic bone", "顴骨"], ["Nasal bone", "鼻骨"]]),
  bone("mandible", "head", "Mandible bone", "Mandible", "下頜骨",
    "The only movable bone of the skull. It carries the lower teeth.",
    "下頜骨是顱骨中唯一可動的骨，承載下排牙齒。",
    [["Mandible", "下頜骨"], ["Maxilla", "上頜骨"], ["Zygomatic bone", "顴骨"], ["Temporal bone", "顳骨"]]),

  bone("atlas", "neck", "Atlas (C1)", "Atlas", "寰椎",
    "The first cervical vertebra supports the skull and lets the head nod.",
    "寰椎是第一頸椎，承托顱骨並允許點頭。",
    [["Atlas", "寰椎"], ["Axis", "樞椎"], ["Seventh cervical vertebra", "第七頸椎"], ["Thoracic vertebra", "胸椎"]]),
  bone("axis", "neck", "Axis (C2)", "Axis", "樞椎",
    "The second cervical vertebra lets the head turn from side to side.",
    "樞椎是第二頸椎，使頭能左右旋轉。",
    [["Axis", "樞椎"], ["Atlas", "寰椎"], ["Seventh cervical vertebra", "第七頸椎"], ["First thoracic vertebra", "第一胸椎"]]),
  study("back-muscles", "neck", "back-muscles",
    "Which set of muscles is this model built to show?",
    "這個模型要展示的是哪一組肌肉？",
    "Muscles of the thorax, abdomen and back", "胸、腹與背部的肌肉",
    "The same trunk-muscle model is used for the neck and back, the thorax, and the abdomen.",
    "胸、腹與背部的肌肉是同一模型，頸背、胸與腹都用它。",
    muscles),
  study("back-attachments", "neck", "back-attachments",
    "What do the marks on these bones show?",
    "這些骨上的標記表示什麼？",
    "Muscle origins and insertions", "肌肉的起點與止點",
    "Origins and insertions are the sites where a muscle attaches to bone.",
    "起點與止點是肌肉附著於骨的位置。",
    attachments),
  study("cord-arteries", "neck", "spinal-cord",
    "Which vessels run along the spinal cord in this section?",
    "這個切面裡，沿脊髓走行的是哪些血管？",
    "Anterior and posterior radicular arteries", "脊髓前、後根動脈",
    "The section includes the anterior and posterior radicular arteries beside the cord.",
    "這個切面在脊髓旁標出了脊髓前根動脈與後根動脈。",
    [["Anterior and posterior radicular arteries", "脊髓前、後根動脈"], ["Inferior epigastric arteries", "腹壁下動脈"], ["Coronary arteries", "冠狀動脈"], ["External carotid arteries", "頸外動脈"]]),

  bone("manubrium", "thorax", "Manubrium of sternum", "Manubrium", "胸骨柄",
    "The upper part of the sternum, where the clavicles and the first ribs meet.",
    "胸骨柄是胸骨上部，鎖骨與第一肋在此相接。",
    [["Manubrium", "胸骨柄"], ["Body of the sternum", "胸骨體"], ["Clavicle", "鎖骨"], ["First rib", "第一肋"]]),
  bone("rib", "thorax", "Rib (5th).r", "Fifth rib", "第五肋",
    "This rib arches from the vertebral column toward the sternum.",
    "第五肋自脊柱弓向前方，朝向胸骨。",
    [["Fifth rib", "第五肋"], ["Costal cartilage", "肋軟骨"], ["Sternum", "胸骨"], ["Clavicle", "鎖骨"]]),
  bone("cartilage", "thorax", "Costal cart of 5th rib.r", "Costal cartilage", "肋軟骨",
    "This flexible bar joins the rib to the sternum.",
    "肋軟骨有彈性，將肋骨連於胸骨。",
    [["Costal cartilage", "肋軟骨"], ["Fifth rib", "第五肋"], ["Manubrium", "胸骨柄"], ["Clavicle", "鎖骨"]]),
  bone("rib1", "thorax", "Rib (1st).r", "First rib", "第一肋",
    "The highest rib. It is short, flat, and sits at the root of the neck.",
    "第一肋最短而扁平，位於頸根。",
    [["First rib", "第一肋"], ["Twelfth rib", "第十二肋"], ["Clavicle", "鎖骨"], ["Manubrium", "胸骨柄"]]),
  bone("rib12", "thorax", "Rib (12th).r", "Twelfth rib", "第十二肋",
    "The last rib is short and floats free of the sternum, low on the flank.",
    "第十二肋較短，不連胸骨，位於腰側。",
    [["Twelfth rib", "第十二肋"], ["First rib", "第一肋"], ["Fifth rib", "第五肋"], ["Costal cartilage", "肋軟骨"]]),
  study("thorax-muscles", "thorax", "thorax-muscles",
    "Which set of muscles is this model built to show?",
    "這個模型要展示的是哪一組肌肉？",
    "Muscles of the thorax, abdomen and back", "胸、腹與背部的肌肉",
    "The thoracic wall and the back share this trunk-muscle model.",
    "胸壁與背部共用這個軀幹肌肉模型。",
    muscles),
  study("thorax-attachments", "thorax", "thorax-attachments",
    "What do the marks on these bones show?",
    "這些骨上的標記表示什麼？",
    "Muscle origins and insertions", "肌肉的起點與止點",
    "The marks are the bony attachments of the trunk muscles.",
    "這些標記是軀幹肌肉在骨上的附著處。",
    attachments),

  bone("abdomen-l3", "abdomen", "Lumbar vertebrae (L3)", "Third lumbar vertebra", "第三腰椎",
    "The lumbar spine is the bony column behind the abdomen.",
    "腰椎是腹部後方的骨性支柱。",
    [["Third lumbar vertebra", "第三腰椎"], ["Twelfth rib", "第十二肋"], ["Sacrum", "薦骨"], ["Fifth rib", "第五肋"]]),
  study("abdomen-muscles", "abdomen", "abdomen-muscles",
    "Which set of muscles is this model built to show?",
    "這個模型要展示的是哪一組肌肉？",
    "Muscles of the thorax, abdomen and back", "胸、腹與背部的肌肉",
    "The abdominal wall is part of the same trunk-muscle model.",
    "腹壁屬於同一套胸、腹與背部肌肉模型。",
    muscles),
  study("abdomen-attachments", "abdomen", "abdomen-attachments",
    "What do the marks on these bones show?",
    "這些骨上的標記表示什麼？",
    "Muscle origins and insertions", "肌肉的起點與止點",
    "The marks show where the trunk muscles attach.",
    "這些標記顯示軀幹肌肉的附著位置。",
    attachments),
  study("epigastric", "abdomen", "inguinal-canal",
    "Which artery is the key vessel beside the deep inguinal ring in this model?",
    "在這個模型裡，緊鄰腹股溝深環的關鍵動脈是哪一條？",
    "Inferior epigastric artery", "腹壁下動脈",
    "The inferior epigastric artery ascends beside the deep inguinal ring.",
    "腹壁下動脈在腹股溝深環旁上行。",
    [["Inferior epigastric artery", "腹壁下動脈"], ["Radial artery", "橈動脈"], ["Coronary artery", "冠狀動脈"], ["Anterior tibial artery", "脛前動脈"]]),
  study("corona", "abdomen", "inguinal-hernia",
    "The link between the inferior epigastric and obturator arteries in this model is the:",
    "這個模型裡，腹壁下動脈與閉孔動脈之間的連接稱為：",
    "Corona mortis", "死亡冠",
    "Corona mortis is that anastomosis. It can bleed in hernia surgery behind the pubis.",
    "死亡冠就是這段吻合。疝修補時，它可能在恥骨後方出血。",
    [["Corona mortis", "死亡冠"], ["Circle of Willis", "大腦動脈環"], ["Inguinal ligament", "腹股溝韌帶"], ["Ligament of Treitz", "十二指腸懸韌帶"]]),
  study("inguinal-ligament", "abdomen", "inguinal-ligament",
    "The ligament from the anterior superior iliac spine toward the pubic tubercle is the:",
    "從髂前上棘走向恥骨結節的韌帶是：",
    "Inguinal ligament", "腹股溝韌帶",
    "The inguinal ligament is the folded lower edge of the external oblique aponeurosis.",
    "腹股溝韌帶是腹外斜肌腱膜下緣折返而成。",
    [["Inguinal ligament", "腹股溝韌帶"], ["Sacrotuberous ligament", "骶結節韌帶"], ["Patellar ligament", "髕韌帶"], ["Coracoclavicular ligament", "喙鎖韌帶"]]),

  bone("hip", "pelvis", "Hip bone.r", "Hip bone", "髖骨",
    "Ilium, ischium, and pubis fuse into the bone that meets the femur.",
    "髂骨、坐骨與恥骨融為髖骨，並與股骨相接。",
    [["Hip bone", "髖骨"], ["Sacrum", "薦骨"], ["Femur", "股骨"], ["Coccyx", "尾骨"]]),
  bone("sacrum", "pelvis", "Sacrum", "Sacrum", "薦骨",
    "Five fused vertebrae lock the spine between the hip bones.",
    "薦骨由五塊椎骨融合而成，嵌在兩側髖骨之間。",
    [["Sacrum", "薦骨"], ["Coccyx", "尾骨"], ["Lumbar vertebra", "腰椎"], ["Hip bone", "髖骨"]]),
  bone("coccyx", "pelvis", "Coccyx", "Coccyx", "尾骨",
    "The small terminal piece of the column, below the sacrum.",
    "尾骨是脊柱末端的小椎骨，位於薦骨下方。",
    [["Coccyx", "尾骨"], ["Sacrum", "薦骨"], ["Hip bone", "髖骨"], ["Fifth lumbar vertebra", "第五腰椎"]]),
  study("pelvic-floor", "pelvis", "pelvic-floor",
    "Which region does this model close at the outlet of the pelvis?",
    "這個模型展示的是封閉骨盆下口的哪一區？",
    "Pelvis and perineum", "骨盆與會陰",
    "The pelvic floor and perineum close the outlet of the pelvis.",
    "盆底與會陰封閉骨盆的下口。",
    [["Pelvis and perineum", "骨盆與會陰"], ["Rotator cuff", "旋轉袖"], ["Posterior leg", "小腿後群"], ["Brachial plexus", "臂神經叢"]]),
  study("pelvis-attachments", "pelvis", "pelvis-attachments",
    "What do the marks on these bones show?",
    "這些骨上的標記表示什麼？",
    "Muscle origins and insertions", "肌肉的起點與止點",
    "Around the pelvis the marks are still muscle attachments.",
    "骨盆周圍的標記同樣是肌肉的起止點。",
    attachments),

  bone("clavicle", "upper", "Clavicle.r", "Clavicle", "鎖骨",
    "It braces the shoulder girdle away from the trunk.",
    "鎖骨把肩帶撐離軀幹。",
    [["Clavicle", "鎖骨"], ["Scapula", "肩胛骨"], ["Humerus", "肱骨"], ["Sternum", "胸骨"]]),
  bone("scapula", "upper", "Scapula.r.", "Scapula", "肩胛骨",
    "The shoulder blade lies on the back of the chest. Turn the model to see its flat surface.",
    "肩胛骨貼於胸廓後方。把模型轉到背面可看見其扁平面。",
    [["Scapula", "肩胛骨"], ["Clavicle", "鎖骨"], ["Humerus", "肱骨"], ["Rib", "肋骨"]]),
  bone("humerus", "upper", "Humerus.r", "Humerus", "肱骨",
    "The arm bone runs from the shoulder joint to the elbow.",
    "肱骨是上臂的長骨，上接肩關節，下接肘關節。",
    [["Humerus", "肱骨"], ["Radius", "橈骨"], ["Ulna", "尺骨"], ["Femur", "股骨"]]),
  bone("radius", "upper", "Radius.r", "Radius", "橈骨",
    "The lateral forearm bone. It crosses the ulna as the palm turns.",
    "橈骨位於前臂外側，掌心翻轉時繞尺骨旋轉。",
    [["Radius", "橈骨"], ["Ulna", "尺骨"], ["Humerus", "肱骨"], ["Fibula", "腓骨"]]),
  bone("ulna", "upper", "Ulna.r", "Ulna", "尺骨",
    "The medial forearm bone. Its olecranon is the point of the elbow.",
    "尺骨位於前臂內側，鷹嘴構成肘尖。",
    [["Ulna", "尺骨"], ["Radius", "橈骨"], ["Humerus", "肱骨"], ["Tibia", "脛骨"]]),
  bone("metacarpal", "upper", "3rd metacarpal bone.r", "Metacarpal", "掌骨",
    "The metacarpals form the skeleton of the palm, beyond the wrist.",
    "掌骨構成手掌的骨架，位於腕骨遠側。",
    [["Metacarpal", "掌骨"], ["Carpal bone", "腕骨"], ["Phalanx", "指骨"], ["Radius", "橈骨"]]),
  study("rotator-cuff", "upper", "rotator-cuff",
    "Which muscles does this model gather around the shoulder?",
    "這個模型在肩關節周圍集合的是哪一組肌肉？",
    "Rotator cuff", "旋轉袖",
    "The cuff is supraspinatus, infraspinatus, teres minor, and subscapularis.",
    "旋轉袖包括岡上肌、岡下肌、小圓肌與肩胛下肌。",
    [["Rotator cuff", "旋轉袖"], ["Quadriceps", "股四頭肌"], ["Hamstrings", "膕繩肌"], ["Erector spinae", "豎脊肌"]]),

  bone("femur", "lower", "Femur.r", "Femur", "股骨",
    "The thigh bone is the longest bone in the body. It runs from hip to knee.",
    "股骨是全身最長的骨，從髖關節連到膝關節。",
    [["Femur", "股骨"], ["Tibia", "脛骨"], ["Fibula", "腓骨"], ["Humerus", "肱骨"]]),
  bone("patella", "lower", "Patella.r", "Patella", "髕骨",
    "The kneecap sits in the tendon in front of the knee.",
    "髕骨位於膝前方的肌腱之中。",
    [["Patella", "髕骨"], ["Tibia", "脛骨"], ["Femur", "股骨"], ["Fibula", "腓骨"]]),
  bone("tibia", "lower", "Tibia.r", "Tibia", "脛骨",
    "The shin bone carries the body's weight from the knee to the ankle.",
    "脛骨把體重從膝關節傳到踝關節。",
    [["Tibia", "脛骨"], ["Fibula", "腓骨"], ["Femur", "股骨"], ["Patella", "髕骨"]]),
  bone("fibula", "lower", "Fibula.r", "Fibula", "腓骨",
    "The slender bone on the outer side of the leg.",
    "腓骨是小腿外側細長的骨。",
    [["Fibula", "腓骨"], ["Tibia", "脛骨"], ["Femur", "股骨"], ["Radius", "橈骨"]]),
  bone("calcaneus", "lower", "Calcaneus.r", "Calcaneus", "跟骨",
    "The heel bone meets the ground at the back of the foot.",
    "跟骨在足後端接觸地面。",
    [["Calcaneus", "跟骨"], ["Talus", "距骨"], ["First metatarsal", "第一蹠骨"], ["Tibia", "脛骨"]]),
  bone("metatarsal", "lower", "First metatarsal bone.r", "First metatarsal", "第一蹠骨",
    "It forms the bony base of the great toe.",
    "第一蹠骨構成踇趾的骨性基底。",
    [["First metatarsal", "第一蹠骨"], ["Calcaneus", "跟骨"], ["Talus", "距骨"], ["Tibia", "脛骨"]]),
  study("abductors", "lower", "abductors",
    "The gluteal muscles in this model mainly:",
    "這個模型裡的臀肌主要做什麼？",
    "Abduct and laterally rotate the thigh", "外展並外旋大腿",
    "The abductors and lateral rotators sit in the gluteal region.",
    "外展肌與外旋肌位於臀區。",
    [["Abduct and laterally rotate the thigh", "外展並外旋大腿"], ["Flex the elbow", "屈肘"], ["Extend the knee only", "只伸膝"], ["Adduct the thigh", "內收大腿"]]),
  study("knee-extensors", "lower", "knee-extensors",
    "The large anterior thigh muscle that extends the knee is the:",
    "伸膝的大腿前方大肌是：",
    "Quadriceps femoris", "股四頭肌",
    "Quadriceps femoris is the extensor of the knee.",
    "股四頭肌是膝關節的伸肌。",
    [["Quadriceps femoris", "股四頭肌"], ["Hamstrings", "膕繩肌"], ["Triceps brachii", "肱三頭肌"], ["Biceps brachii", "肱二頭肌"]]),
  study("hip-flexors", "lower", "hip-flexors",
    "The anterior thigh muscles in this model mainly:",
    "這個模型裡的大腿前方肌肉主要做什麼？",
    "Flex the hip", "屈髖",
    "The anterior thigh group includes the flexors of the hip joint.",
    "大腿前方肌群包含髖關節的屈肌。",
    [["Flex the hip", "屈髖"], ["Extend the hip", "伸髖"], ["Plantarflex the foot", "跖屈足"], ["Extend the wrist", "伸腕"]]),
  study("posterior-leg", "lower", "leg-posterior",
    "The superficial muscles of the posterior leg mainly:",
    "小腿後群淺層肌肉主要做什麼？",
    "Plantarflex the foot", "跖屈足",
    "Gastrocnemius and soleus plantarflex the foot and raise the heel.",
    "腓腸肌與比目魚肌跖屈足並提起足跟。",
    [["Plantarflex the foot", "跖屈足"], ["Dorsiflex the foot", "背屈足"], ["Extend the knee", "伸膝"], ["Flex the elbow", "屈肘"]]),

  study("plexus-roots", "nerves", "brachial-plexus",
    "The brachial plexus is formed by the ventral rami of:",
    "臂神經叢由哪些脊神經前支組成？",
    "C5 to T1", "第五頸神經至第一胸神經",
    "The roots of the brachial plexus are the ventral rami of C5 to T1.",
    "臂神經叢的根是第五頸神經到第一胸神經的前支。",
    [["C5 to T1", "第五頸神經至第一胸神經"], ["C1 to C4", "第一至第四頸神經"], ["T2 to T6", "第二至第六胸神經"], ["L2 to L4", "第二至第四腰神經"]]),
  study("plexus-branch", "nerves", "brachial-branches",
    "Which nerve is a terminal branch of the brachial plexus?",
    "哪一條是臂神經叢的終支？",
    "Median nerve", "正中神經",
    "The terminal branches include the musculocutaneous, axillary, radial, median, and ulnar nerves.",
    "終支包括肌皮神經、腋神經、橈神經、正中神經與尺神經。",
    [["Median nerve", "正中神經"], ["Femoral nerve", "股神經"], ["Sciatic nerve", "坐骨神經"], ["Phrenic nerve", "膈神經"]]),
  study("axillary-nerve", "nerves", "axillary-nerve",
    "The axillary nerve winds the surgical neck of the humerus and supplies the:",
    "腋神經繞過肱骨外科頸，支配：",
    "Deltoid", "三角肌",
    "The axillary nerve supplies deltoid and teres minor.",
    "腋神經支配三角肌與小圓肌。",
    [["Deltoid", "三角肌"], ["Biceps brachii", "肱二頭肌"], ["Triceps brachii", "肱三頭肌"], ["Flexor carpi ulnaris", "尺側腕屈肌"]]),
  study("radial-nerve", "nerves", "radial-nerve",
    "The radial nerve supplies the:",
    "橈神經支配：",
    "Extensors of the wrist and fingers", "腕與指的伸肌",
    "The radial nerve supplies the extensors in the posterior arm and forearm.",
    "橈神經支配臂與前臂後群的伸肌。",
    [["Extensors of the wrist and fingers", "腕與指的伸肌"], ["Thenar muscles", "魚際肌"], ["Hypothenar muscles", "小魚際肌"], ["Biceps brachii", "肱二頭肌"]]),
  study("ulnar-nerve", "nerves", "ulnar-nerve",
    "The ulnar nerve passes behind the:",
    "尺神經從哪一個骨性標誌的後方經過？",
    "Medial epicondyle of the humerus", "肱骨內上髁",
    "Behind the medial epicondyle is the common site where the ulnar nerve is bumped.",
    "肱骨內上髁後方是尺神經容易被碰到的位置。",
    [["Medial epicondyle of the humerus", "肱骨內上髁"], ["Lateral epicondyle of the humerus", "肱骨外上髁"], ["Olecranon of the ulna only", "只經過尺骨鷹嘴"], ["Coracoid process", "喙突"]]),
  study("median-nerve", "nerves", "median-nerve",
    "The median nerve enters the hand through the:",
    "正中神經經由哪一個通道進入手？",
    "Carpal tunnel", "腕管",
    "The median nerve passes through the carpal tunnel, deep to the flexor retinaculum.",
    "正中神經在屈肌支持帶深面穿過腕管。",
    [["Carpal tunnel", "腕管"], ["Guyon's canal", "尺管"], ["Inguinal canal", "腹股溝管"], ["Adductor canal", "收肌管"]]),
  study("musculocutaneous-nerve", "nerves", "musculocutaneous-nerve",
    "The musculocutaneous nerve supplies the:",
    "肌皮神經支配：",
    "Biceps brachii", "肱二頭肌",
    "It supplies coracobrachialis, biceps brachii, and brachialis.",
    "肌皮神經支配喙肱肌、肱二頭肌與肱肌。",
    [["Biceps brachii", "肱二頭肌"], ["Deltoid", "三角肌"], ["Triceps brachii", "肱三頭肌"], ["Interossei", "骨間肌"]]),

  study("radicular", "vessels", "vessels-cord",
    "Which vessels run along the spinal cord in this section?",
    "這個切面裡，沿脊髓走行的是哪些血管？",
    "Anterior and posterior radicular arteries", "脊髓前、後根動脈",
    "There is no separate whole-body circulation model. These radicular arteries are the published vessels beside the cord.",
    "學習目錄裡沒有單獨的全身循環模型。脊髓旁已發表的血管就是這些根動脈。",
    [["Anterior and posterior radicular arteries", "脊髓前、後根動脈"], ["Inferior epigastric arteries", "腹壁下動脈"], ["Coronary arteries", "冠狀動脈"], ["Popliteal artery", "膕動脈"]]),
  study("epigastric-origin", "vessels", "vessels-inguinal",
    "The inferior epigastric artery usually arises from the:",
    "腹壁下動脈通常起自：",
    "External iliac artery", "髂外動脈",
    "The inferior epigastric artery leaves the external iliac artery just above the inguinal ligament.",
    "腹壁下動脈在腹股溝韌帶上方起自髂外動脈。",
    [["External iliac artery", "髂外動脈"], ["Internal carotid artery", "頸內動脈"], ["Subclavian artery", "鎖骨下動脈"], ["Popliteal artery", "膕動脈"]]),
  study("corona-vessel", "vessels", "vessels-hernia",
    "In this hernia model, the anastomosis that can bleed behind the pubis is the:",
    "在這個疝修補模型裡，可能在恥骨後方出血的吻合是：",
    "Corona mortis", "死亡冠",
    "Corona mortis joins the inferior epigastric artery with the obturator artery.",
    "死亡冠連接腹壁下動脈與閉孔動脈。",
    [["Corona mortis", "死亡冠"], ["Circle of Willis", "大腦動脈環"], ["Arcus palmaris", "掌淺弓"], ["Inguinal ligament", "腹股溝韌帶"]]),
];

export function questionById(id) {
  return QUESTIONS.find((question) => question.id === id);
}

export function questionsForTopic(topicId) {
  return QUESTIONS.filter((question) => question.topicId === topicId);
}

export function mixedRound(count = 12) {
  const picked = [];
  for (const topic of TOPICS) {
    const list = questionsForTopic(topic.id);
    if (!list.length) continue;
    picked.push(list[Math.floor(Math.random() * list.length)]);
  }
  const rest = QUESTIONS.filter((question) => !picked.includes(question));
  for (let i = rest.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    [rest[i], rest[j]] = [rest[j], rest[i]];
  }
  return picked.concat(rest).slice(0, count);
}
